name: native_pty
description: A native pseudo-terminal library for Dart using FFI
version: 0.0.1
# repository: https://github.com/few-sh/native_pty

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  ffi: ^2.1.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.6
